# Generated by Django 2.1 on 2018-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
