# Generated by Django 2.1 on 2018-09-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyBook',
            fields=[
                ('copyBookName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('coverImgUrl', models.CharField(max_length=100)),
                ('contentImgUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
