# Generated by Django 2.1 on 2018-09-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180924_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copybook',
            name='contentImgUrl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='copybook',
            name='copyBookName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='copybook',
            name='coverImgUrl',
            field=models.URLField(),
        ),
    ]
