# Generated by Django 2.1 on 2018-09-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180924_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copybook',
            name='contentImgUrl',
        ),
    ]
