# Generated by Django 2.1 on 2018-09-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_copybook_contentimgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='copybook',
            name='contentImgUrl',
            field=models.URLField(auto_created=True, default=2),
            preserve_default=False,
        ),
    ]
