# Generated by Django 2.1 on 2018-09-24 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_copybook_contentimgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyBookAll',
            fields=[
                ('contentImgUrl', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CopyBookList',
            fields=[
                ('copyBookName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='CopyBook',
        ),
        migrations.AddField(
            model_name='copybookall',
            name='CopyBookEachName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CopyBookList'),
        ),
    ]
