# Generated by Django 2.1 on 2018-09-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20180924_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='copybookall',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='copybookall',
            name='contentImgUrl',
            field=models.URLField(),
        ),
    ]
