# Generated by Django 2.1 on 2018-09-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180925_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copybooklist',
            name='copyBookName',
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
