# Generated by Django 2.1 on 2018-09-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20180925_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='copybooklist',
            name='coverImgUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
