# Generated by Django 2.1 on 2018-09-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_copybooklist_coverimgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copybooklist',
            name='coverImgUrl',
        ),
    ]
