# Generated by Django 2.1 on 2018-09-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_copybooklist_coverimgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorName', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChinesePainting',
            fields=[
                ('PaintingId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('PaintingUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Collectors',
            fields=[
                ('CollectId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('CollectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CopyBookList')),
            ],
        ),
        migrations.CreateModel(
            name='FindWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('UserName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('UserPassword', models.CharField(max_length=100)),
                ('UserAge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordsAll',
            fields=[
                ('WordId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('WordUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WordsList',
            fields=[
                ('WordName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('WordAuthor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WordsOutline',
            fields=[
                ('WordName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('WordAuthor', models.CharField(max_length=50)),
                ('WordUrl', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='wordsall',
            name='WordEachName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.WordsList'),
        ),
        migrations.AddField(
            model_name='findwords',
            name='FindAuthorName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.WordsList'),
        ),
        migrations.AddField(
            model_name='findwords',
            name='FindWordsId',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Author'),
        ),
    ]
