# Generated by Django 2.1 on 2018-09-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20180926_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='findwords',
            name='WordsUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
