# Generated by Django 2.1 on 2018-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_findwords_wordsurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='AuthorWords',
            field=models.ManyToManyField(through='mainapp.FindWords', to='mainapp.Words'),
        ),
    ]
