# Generated by Django 2.1 on 2018-09-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_author_authorwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='UserName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
