# Generated by Django 2.1 on 2018-09-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20180927_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='UserName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
