# Generated by Django 2.1 on 2018-09-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20180927_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='UserAge',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='UserPassword',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
