# Generated by Django 2.1 on 2018-10-01 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20180927_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsCircleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releaseDate', models.DateTimeField(max_length=200)),
                ('ItemText', models.TextField(max_length=500)),
                ('imgUrl', models.URLField(max_length=100)),
                ('stick', models.CharField(max_length=100, null=True)),
                ('likeNum', models.CharField(max_length=100)),
                ('shareNum', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='collectors',
            name='CollectName',
        ),
        migrations.AddField(
            model_name='collectors',
            name='CollectUrl',
            field=models.URLField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='UserAvatar',
            field=models.ImageField(default=0, max_length=500, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='UserPassword',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendscircleitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.MyUser'),
        ),
    ]
