# Generated by Django 2.1 on 2018-10-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20181001_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='UserAvatar',
            field=models.FileField(upload_to='media'),
        ),
    ]
