# Generated by Django 2.1 on 2018-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20181001_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='UserAvatar',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
