# Generated by Django 2.1 on 2018-10-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_hqz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectors',
            name='CollectUrl',
            field=models.FileField(upload_to='media'),
        ),
    ]
