# Generated by Django 2.1 on 2018-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20181007_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectors',
            name='CollectUrl',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='friendscircleitem',
            name='imgUrl',
            field=models.FileField(upload_to='media'),
        ),
    ]
