# Generated by Django 2.1 on 2018-10-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20181007_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='findwords',
            name='Probability',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
