# Generated by Django 2.1 on 2018-10-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_findwords_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendscircleitem',
            name='releaseDate',
            field=models.DateTimeField(max_length=200, null=True),
        ),
    ]
