# Generated by Django 2.1 on 2018-10-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20181008_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendscircleitem',
            name='id',
        ),
        migrations.AddField(
            model_name='friendscircleitem',
            name='friendId',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
