# Generated by Django 2.1 on 2018-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20181008_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendscircleitem',
            name='friendId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
