# Generated by Django 2.1 on 2018-10-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20181008_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectors',
            name='CollectAuthor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectors',
            name='CollectCopyName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
