# Generated by Django 2.1 on 2018-10-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20181009_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='UserId',
            field=models.CharField(default=1, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='UserName',
            field=models.CharField(max_length=100),
        ),
    ]
