# Generated by Django 2.1 on 2018-10-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20181009_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='UserId',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='UserName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
