# Generated by Django 2.2 on 2019-06-21 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20181009_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasesClassify',
            fields=[
                ('diseaseVariety', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('diseaseIntroduce', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EatStatistics',
            fields=[
                ('eatId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('eatHot', models.IntegerField()),
                ('eatProtein', models.IntegerField()),
                ('eatSugar', models.IntegerField()),
                ('eatTime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('foodId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=100)),
                ('foodMaterial', models.CharField(max_length=200)),
                ('foodHot', models.IntegerField()),
                ('foodProtein', models.IntegerField()),
                ('foodIntroduce', models.TextField(max_length=200)),
                ('foodUrl', models.URLField()),
                ('diseaseVariety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.DiseasesClassify')),
            ],
        ),
    ]
