# Generated by Django 2.2 on 2019-07-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_diseasesclassify_eatstatistics_foods_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EatStatistics',
        ),
        migrations.RemoveField(
            model_name='foods',
            name='diseaseVariety',
        ),
        migrations.DeleteModel(
            name='HQZ',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='DiseasesClassify',
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
